In [3]:
!pip install numpy

In [5]:
import numpy as np

In [5]:
a=[1,34,89]
type(a)

list

In [7]:
b=np.array(a)
b

array([ 1, 34, 89])

In [9]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
b.shape

(3, 3)

In [13]:
b.size

9

In [15]:
b.ndim

2

In [17]:
myarr=np.array([[3,6,37,7]],np.int64)
myarr

array([[ 3,  6, 37,  7]], dtype=int64)

In [19]:
myarr[0,1]

6

In [21]:
myarr[0]

array([ 3,  6, 37,  7], dtype=int64)

In [23]:
myarr[0,0]

3

In [25]:
myarr[0,2]

37

In [27]:
myarr.shape

(1, 4)

In [29]:
myarr.dtype

dtype('int64')

In [31]:
myarr[0,1]

6

In [33]:
myarr[0,1]=45

In [35]:
myarr

array([[ 3, 45, 37,  7]], dtype=int64)

In [7]:
#how can we create a user defined array?
a=[]
size=int(input("enter size:"))
for i in range(size):
    val=int(input("enter item:"))
    a.append(val)
b=np.array(a)
b

enter size: 3
enter item: 4
enter item: 8
enter item: 9


array([4, 8, 9])

In [9]:
type(b)

numpy.ndarray

In [11]:
#numpy functions or methods
#(1).zeros()=
a=np.zeros(3)
a

array([0., 0., 0.])

In [13]:
b=np.zeros((1,2,3))
b

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [15]:
#(2).ones()=
a=np.ones(4)
a

array([1., 1., 1., 1.])

In [19]:
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
#(3).eye()=
a=np.eye(3,4) #asymmatric matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [27]:
a=np.eye(3) #symmatric matrix
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
#(4).diag()=
a=np.diag([1,45,78,90])
a

array([[ 1,  0,  0,  0],
       [ 0, 45,  0,  0],
       [ 0,  0, 78,  0],
       [ 0,  0,  0, 90]])

In [38]:
#(5).random module
#(a).randint(min_range,max_range,total_numbers)
np.random.randint(1,10,4)

array([8, 5, 2, 8])

In [40]:
#(b).rand(total_numbers)-->it will return an array from 0-1
a=np.random.rand(5)
a

array([0.41460658, 0.73184816, 0.02054316, 0.78838008, 0.25462629])

In [50]:
#seed() function-->it will fix the data when it is generated
np.random.seed(20)
a=np.random.randint(1,10,3)
a

array([4, 5, 7])

In [52]:
#VIEW VS COPY METHOD
#view method=>
a=np.array([10,20,30,40,50,60,70,80])
b=a[2:5]
b[:]=0
b

array([0, 0, 0])

In [54]:
a

array([10, 20,  0,  0,  0, 60, 70, 80])

In [56]:
#copy method
a=np.array([10,20,30,40,50,60,70,80])
b=a[2:5].copy()
b[:]=0
b

array([0, 0, 0])

In [58]:
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [60]:
#reshaping the array
a=np.random.randint(1,100,12)
a

array([72, 35, 97, 41, 86, 91, 27, 84, 17, 63, 17,  8])

In [62]:
a.reshape(2,6)

array([[72, 35, 97, 41, 86, 91],
       [27, 84, 17, 63, 17,  8]])

In [64]:
a.reshape(6,2)

array([[72, 35],
       [97, 41],
       [86, 91],
       [27, 84],
       [17, 63],
       [17,  8]])

In [66]:
a.reshape(3,4)

array([[72, 35, 97, 41],
       [86, 91, 27, 84],
       [17, 63, 17,  8]])

In [68]:
a.reshape(5,2)

ValueError: cannot reshape array of size 12 into shape (5,2)

In [70]:
#Q.=1-60 and total_elemets=36
a=np.random.randint(1,60,36)
a

array([38, 35,  7, 27, 14, 12, 59, 26,  4, 11, 12, 14, 20, 58, 31, 47, 33,
       11, 44,  7, 12, 19,  4, 14, 18, 57, 44, 17, 19, 16, 27,  8, 12, 55,
       30, 46])

In [72]:
a.reshape(12,3)

array([[38, 35,  7],
       [27, 14, 12],
       [59, 26,  4],
       [11, 12, 14],
       [20, 58, 31],
       [47, 33, 11],
       [44,  7, 12],
       [19,  4, 14],
       [18, 57, 44],
       [17, 19, 16],
       [27,  8, 12],
       [55, 30, 46]])

In [74]:
a.reshape(3,12)

array([[38, 35,  7, 27, 14, 12, 59, 26,  4, 11, 12, 14],
       [20, 58, 31, 47, 33, 11, 44,  7, 12, 19,  4, 14],
       [18, 57, 44, 17, 19, 16, 27,  8, 12, 55, 30, 46]])

In [76]:
a.reshape(6,6)

array([[38, 35,  7, 27, 14, 12],
       [59, 26,  4, 11, 12, 14],
       [20, 58, 31, 47, 33, 11],
       [44,  7, 12, 19,  4, 14],
       [18, 57, 44, 17, 19, 16],
       [27,  8, 12, 55, 30, 46]])

In [78]:
a.reshape(18,2)

array([[38, 35],
       [ 7, 27],
       [14, 12],
       [59, 26],
       [ 4, 11],
       [12, 14],
       [20, 58],
       [31, 47],
       [33, 11],
       [44,  7],
       [12, 19],
       [ 4, 14],
       [18, 57],
       [44, 17],
       [19, 16],
       [27,  8],
       [12, 55],
       [30, 46]])

In [80]:
a.reshape(2,18)

array([[38, 35,  7, 27, 14, 12, 59, 26,  4, 11, 12, 14, 20, 58, 31, 47,
        33, 11],
       [44,  7, 12, 19,  4, 14, 18, 57, 44, 17, 19, 16, 27,  8, 12, 55,
        30, 46]])

In [82]:
 #condition selection in numpy=>
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [84]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [86]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [88]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [106]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [108]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [110]:
a+b

array([[ 6,  8],
       [10, 12]])

In [112]:
a-b

array([[-4, -4],
       [-4, -4]])

In [114]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [118]:
#(6).linspace()=>
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [122]:
#(7).unique()=
a=np.array([1,2,2,2,1,3,4,3,2,2,2,5])
np.unique(a,return_index=True,return_counts=True)
 

(array([1, 2, 3, 4, 5]),
 array([ 0,  1,  5,  6, 11], dtype=int64),
 array([2, 6, 2, 1, 1], dtype=int64))

In [124]:
a=np.random.randint(1,10,9).reshape(3,3)
a

array([[7, 9, 3],
       [2, 4, 3],
       [7, 5, 7]])

In [126]:
np.sum(a,axis=0)

array([16, 18, 13])

In [128]:
np.sum(a,axis=1)

array([19,  9, 19])

In [130]:
np.sum(a)

47

In [134]:
#hstack and vstack=>horizontally and vertically stacking
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [138]:
b=np.arange(5,9)
b

array([5, 6, 7, 8])

In [140]:
c=np.arange(9,13)
c

array([ 9, 10, 11, 12])

In [142]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [144]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])